name: GitHub Flow Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run pytest

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::1234567890:role/pipelines-cd-abc123
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Deploy to Staging
        # env:
        #     TF_VAR_SECRET_DATA: ${{ secrets.SECRET_DATA_STAGING }}
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=staging ./deploy.sh

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::1234567890:role/pipelines-cd-abc123
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Deploy to Production
        # env:
        #   TF_VAR_SECRET_DATA: ${{ secrets.SECRET_DATA_PROD }}
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=prod ./deploy.sh 